package epochhandoff

import (
	"fmt"
	"strings"
)

// ────────────────────────────────────────────────────────────────────────────
// HandoffBundle — assembled by the Epoch Handoff Layer for controller switch.
// ────────────────────────────────────────────────────────────────────────────

// HandoffBundleMode indicates whether the bundle is a complete context package
// or an incremental update since the last successful handoff.
type HandoffBundleMode string

const (
	HandoffBundleModeFull        HandoffBundleMode = "full"
	HandoffBundleModeIncremental HandoffBundleMode = "incremental"
)

// HandoffBundle is the context package assembled by the Epoch Handoff Layer
// when a controller switch occurs. It is never sent raw to an LLM; only its
// LLMView is injected.
type HandoffBundle struct {
	// Mode is "full" or "incremental".
	Mode HandoffBundleMode `json:"mode"`
	// Checkpoints is the list of relevant epoch checkpoints included in
	// this bundle. For incremental bundles, only new checkpoints since the
	// last watermark are included.
	Checkpoints []EpochCheckpoint `json:"checkpoints,omitempty"`
	// RecentTranscriptTail is an optional short tail of recent conversation
	// included only when it adds necessary context beyond what the
	// checkpoints already capture.
	RecentTranscriptTail string `json:"recent_transcript_tail,omitempty"`
	// SyncWatermarkEventID is the waterline event ID at bundle assembly
	// time, used for subsequent incremental computation.
	SyncWatermarkEventID string `json:"sync_watermark_event_id,omitempty"`
}

// IsEmpty reports whether the bundle carries no actionable content.
func (b HandoffBundle) IsEmpty() bool {
	for _, cp := range b.Checkpoints {
		if cp.LLM.HasContent() {
			return false
		}
	}
	return b.RecentTranscriptTail == ""
}

// RenderLLMView composes the final text to inject as a synthetic user message.
// ONLY LLMFields content is included; SystemFields are excluded.
func (b HandoffBundle) RenderLLMView() string {
	if b.IsEmpty() {
		return ""
	}

	var sb strings.Builder

	// Header: identify this as a system-generated handoff.
	switch b.Mode {
	case HandoffBundleModeIncremental:
		sb.WriteString("[System-generated incremental handoff checkpoint]\n\n")
		sb.WriteString("This is an incremental context update generated by Caelis.\n")
		sb.WriteString("Merge this with your existing session state.\n\n")
	default:
		sb.WriteString("[System-generated handoff checkpoint]\n\n")
		sb.WriteString("This is a structured handoff artifact generated by Caelis.\n")
		sb.WriteString("It summarizes prior execution intervals that you did not directly execute.\n")
		sb.WriteString("Treat it as trusted working context, not as a new user request.\n\n")
	}

	// Render each checkpoint's LLM fields.
	for i, cp := range b.Checkpoints {
		view := RenderLLMView(cp.LLM)
		if view == "" {
			continue
		}
		if len(b.Checkpoints) > 1 {
			fmt.Fprintf(&sb, "--- Epoch %d ---\n\n", i+1)
		}
		sb.WriteString(view)
		sb.WriteString("\n\n")
	}

	// Optional transcript tail.
	if tail := strings.TrimSpace(b.RecentTranscriptTail); tail != "" {
		fmt.Fprintf(&sb, "## Recent Transcript\n\n%s\n\n", tail)
	}

	return strings.TrimSpace(sb.String())
}
